### ISSUE TITLE
exportToJson and importFromJson not working with REAL type

### ISSUE THREAD

**Issue by yganatra1** [jepiqueau/vue-sqlite-hook#2]
Tried using exportToJson and importFromJson its working fine with INTEGER and TEXT type but not working with REAL Type,
I also checked vue-sqlite-app-startar, REAL type is never used in the demo as well.

Steps:

1. Prepare any SQLite DB with Real Type
2. Try to use exportToJSON or importFromJson.
3. It will give an error ( Note: In Export It won't give an error but the values will be emitted from the exported JSON )

example JSON: 
```{
    database : "db-from-json",
    version: 1,
    encrypted : false,
    mode : "full",
    tables :[
        {
            name: "users",
            schema: [
                {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
                {column:"email", value:"TEXT UNIQUE NOT NULL"},
                {column:"name", value:"TEXT"},
                {column:"age", value:"REAL"},
                {column:"last_modified", value:"INTEGER"}
            ],
            indexes: [
                {name: "index_user_on_name",column: "name"},
                {name: "index_user_on_last_modified",column: "last_modified"}
            ],
            values: [
                [1,"Whiteley.com","Whiteley",30.1,1582536810],
                [2,"Jones.com","Jones",44,1582812800],
                [3,"Simpson@example.com","Simpson",69,1583570630],
                [4,"Brown@example.com","Brown",15,1590383895]
            ]
        },
        {
          name: "messages",
          schema: [
            {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
            {column:"title", value:"TEXT NOT NULL"},
            {column:"body", value:"TEXT NOT NULL"},
            {column:"last_modified", value:"INTEGER"}
          ],
          values: [
              [1,"test post 1","content test post 1",1587310030],
              [2,"test post 2","content test post 2",1590388125]
          ]
        },
        {
          name: "images",
          schema: [
            {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
            {column:"name", value:"TEXT UNIQUE NOT NULL"},
            {column:"type", value:"TEXT NOT NULL"},
            {column:"size", value:"INTEGER"},
            {column:"img", value:"BLOB"},
            {column:"last_modified", value:"INTEGER"}
          ],
          values: [
            [1,"feather","png","NULL",Images[1],1582536810],
            [2,"meowth","png","NULL",Images[0],1590151132]
          ]
        }

    ]
}```

**Comment by jepiqueau** [comment]
@mouse9 Are you using the refactor 2.9.4 or the original 2.4.5 of @capacitor-community/sqlite? On which platform it happens iOS, Android, Electron ?

**Comment by yganatra1** [comment]
@jepiqueau I am using this "@capacitor-community/sqlite": "^2.4.5-3",
and I have checked in Android, haven't checked with the other two.
In Fact, it's reproducible with the same import JSON with REAL type in this Repository.
 https://github.com/jepiqueau/vue-sqlite-app-starter
 
 I have shared the above JSON from this repository only.

**Comment by jepiqueau** [comment]
@mouse9 i solve it in the coming `refactor` 2.9.5 release, i will invite you to start looking at migrating to the refactor release and test it on `https://github.com/jepiqueau/vue-sqlite-app-starter` refactor branch. The plugin interface has changed but it will be the one to use when upgrading to capacitor3. It is well documented, but if you need some help do not hesitate to contact me
