### ISSUE TITLE
[Quasar] boot error: TypeError: Cannot destructure property 'onProgressImport' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by ajmas** [jepiqueau/vue-sqlite-hook#4]
Trying to run this with Capacitor 3 and Quasar, but getting, when running in the device emulator of Android Studio.

```
webpack-internal:///./.quasar/client-entry.js:78 [Quasar] boot error: TypeError: Cannot destructure property 'onProgressImport' of 'undefined' as it is undefined.
    at useSQLite (webpack-internal:///./node_modules/vue-sqlite-hook/dist/useSQLite.js:20)
    at DatabaseService.init (webpack-internal:///./src/api/services/DatabaseService.js:24)
    at Array.eval (webpack-internal:///./src/boot/api.js:18)
    at async start (webpack-internal:///./.quasar/client-entry.js:63)
```

The code at line 24 corresponds to:

```js
this.database = (0,vue_sqlite_hook_dist__WEBPACK_IMPORTED_MODULE_1__.useSQLite)();
```

Was basing myself off example here:

https://github.com/jepiqueau/vue-sqlite-app/blob/99fca296e446549ea8afd40c418d7af4f9a4af0e/src/components/NoEncryptionTest.vue

Any ideas?

**Comment by ajmas** [comment]
Okay, so it looks like we need to provide an empty json:

```
useSQLite({})
```

I suspect the function in the source should be default to an empty json, to remain compatible?

```ts
export function useSQLite({
    onProgressImport,
    onProgressExport
}: SQLiteProps = {}): SQLiteHook {
```

**Comment by jepiqueau** [comment]
@ajmas can you share your package.json and the code where use useSQLite

**Comment by jepiqueau** [comment]
@ajmas onProgressImport and onProgressExport are two listeners. So look at vue-sqlite-app-starter

**Comment by ajmas** [comment]
The issue here is if we don’t pass in an empty object, then we can’t deconstruct an undefined value. Hence the suggestion for providing a default value. 

I was using @next for version. 

I was looking at the vue-sqlite-app-starter.

**Comment by jepiqueau** [comment]
@ajmas i have updated `https://github.com/jepiqueau/vue-sqlite-app` to Capacitor 3.1.1, @capacitor-community/sqlite 3.1.2-1 and vue-sqlite-hook 2.0.4 and use 
```
    const { echo, createConnection, closeConnection} = useSQLite({});

```
and it works fine. Hope this will help you to solve your issue

**Comment by jepiqueau** [comment]
@ajmas I do not know the Quasar Framework

**Comment by ajmas** [comment]
Quasar is really incidental here.

Thanks for updating the example.

**Comment by Atom02** [comment]
@jepiqueau 
@ajmas do you get it to work on quasar? i am stuck on this.. the useSQLite({}); always return featureNotAvailableError();

![image](https://user-images.githubusercontent.com/497387/133564854-0ebe5612-4ff1-41e3-88d1-1b4519efb747.png)

console.log(useSQLite({})
![image](https://user-images.githubusercontent.com/497387/133564510-22e93be5-63e3-495c-aee8-9cc2150a28fd.png)

**Comment by jepiqueau** [comment]
@Atom02 Can you share your package.json and your App.vue

**Comment by Atom02** [comment]
hi @jepiqueau 

App.Vue
```
<template>
  <router-view />
</template>
<script>
import { defineComponent, getCurrentInstance, onMounted } from "vue";
import { useSQLite } from "vue-sqlite-hook/dist";

export default defineComponent({
  name: "App",
  setup() {
    const app = getCurrentInstance();

    onMounted(async () => {
      console.log("APP.vue");
      console.log("uu", useSQLite({}));
    });
    return {};
  }
});
</script>
```

my package.json 
```
"dependencies": {
    "@capacitor-community/sqlite": "^3.2.2-3",
    "@quasar/extras": "^1.10.12",
    "axios": "^0.21.4",
    "axios-auth-refresh": "^3.1.0",
    "axios-cache-adapter": "^2.7.3",
    "core-js": "^3.17.3",
    "jeep-sqlite": "^1.2.1",
    "localbase": "^0.7.5",
    "luxon": "^2.0.2",
    "quasar": "^2.0.4",
    "vue-i18n": "^9.1.7",
    "vuex": "^4.0.1",
    "vuex-persistedstate": "^4.0.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.15.4",
    "@quasar/app": "^3.1.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^7.17.0",
    "eslint-webpack-plugin": "^2.4.0",
    "vue-i18n-extract": "^2.0.4",
    "vue-sqlite-hook": "^2.0.8"
  },
```

**Comment by ajmas** [comment]
@Atom02 I did, but i have since moved to using Typeorm. I'll need to dig through my git history.

The issue originally reported in this ticket is because the previous of examples had `useSQLite()` taking no parameters, while the destructing in the function assumes an object is passed in, even if it is empty. I'd have wanted `useSQLite()` to support an `undefined` object parameter, but that isn't the way it is coded.

**Comment by Atom02** [comment]
> @Atom02 I did, but i have since moved to using Typeorm. I'll need to dig through my git history.
> 
> The issue originally reported in this ticket is because the previous of examples had `useSQLite()` taking no parameters, while the destructing in the function assumes an object is passed in, even if it is empty. I'd have wanted `useSQLite()` to support an `undefined` object parameter, but that isn't the way it is coded.

That is also what bring me here.. but after given an empty object as parameter, the useSQLite returns:
![133564510-22e93be5-63e3-495c-aee8-9cc2150a28fd](https://user-images.githubusercontent.com/497387/133709395-3dd08305-65cc-467f-a508-c17f57f8fc97.png)

I hope @jepiqueau have some answers for this

**Comment by jepiqueau** [comment]
@Atom02 Can you share your app on github as i cannot reproduce this with `useSQLite({})` for me it is working find. i did not see @capacitor/core in your package.json file. Have you run 
```
npx cap sync
npm run build
npx cap copy web
``` 
after you have install your app ?

**Comment by jepiqueau** [comment]
@Atom02 see [vue-sqlite-app-hook-issue4](https://github.com/jepiqueau/vue-sqlite-app-hook-issue4) Hope this will help to close the issue

**Comment by Atom02** [comment]
> @Atom02 see [vue-sqlite-app-hook-issue4](https://github.com/jepiqueau/vue-sqlite-app-hook-issue4) Hope this will help to close the issue

hi @jepiqueau thank you for you responses.. i am currently using quasar.. the capacitor is installed on sub folder called src-capacitor.. ill try make skeleton project for you

**Comment by Atom02** [comment]
ok i got it work on quasar...
first off you need to install sqlite plugin on capacitor folder on `src-capacitor` make sure you use version 3
then in that folder do `npx cap sync` after that you rebuild android with `quasar -m capacitor -T android`.

for `vue-sqlite-hook` you install it on root folder..

thanks a lot @jepiqueau your responses give me some direction to solve this

**Comment by jepiqueau** [comment]
@Atom02 I am please that you find your way with quasar. I do not know anything about it
